"""add operation_work_stations

Revision ID: 0cda29e0e850
Revises: 43985d47f2a9
Create Date: 2026-08-07 14:01:12.769803
"""
from alembic import op
import sqlalchemy as sa


revision = '0cda29e0e850'
down_revision = '43985d47f2a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_work_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('work_station_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_station_id'], ['work_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id', 'work_station_id', name='uq_operation_work_station')
    )
    # ### end Alembic commands ###

    # 数据迁移：每个现有 operation 插一条 (operation_id, default_work_station_id)
    op.execute(sa.text("""
        INSERT INTO operation_work_stations (operation_id, work_station_id, created_at, updated_at)
        SELECT id, default_work_station_id, now(), now() FROM operations
    """))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_work_stations')
    # ### end Alembic commands ###
