"""add erp fields to product bom routing

Revision ID: 20fc7d5e9c59
Revises: 3cc26e0832b0
Create Date: 2026-08-05 11:27:46.406863
"""
from alembic import op
import sqlalchemy as sa


revision = '20fc7d5e9c59'
down_revision = '3cc26e0832b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boms', sa.Column('source', sa.String(), server_default='manual', nullable=False))
    op.add_column('boms', sa.Column('erp_ref', sa.String(), nullable=True))
    op.add_column('boms', sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_boms_erp_ref'), 'boms', ['erp_ref'], unique=False)
    op.create_index('uq_boms_erp_ref', 'boms', ['erp_ref'], unique=True, postgresql_where=sa.text('erp_ref IS NOT NULL'))
    op.add_column('products', sa.Column('source', sa.String(), server_default='manual', nullable=False))
    op.add_column('products', sa.Column('erp_ref', sa.String(), nullable=True))
    op.add_column('products', sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_products_erp_ref'), 'products', ['erp_ref'], unique=False)
    op.create_index('uq_products_erp_ref', 'products', ['erp_ref'], unique=True, postgresql_where=sa.text('erp_ref IS NOT NULL'))
    op.add_column('routings', sa.Column('source', sa.String(), server_default='manual', nullable=False))
    op.add_column('routings', sa.Column('erp_ref', sa.String(), nullable=True))
    op.add_column('routings', sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_routings_erp_ref'), 'routings', ['erp_ref'], unique=False)
    op.create_index('uq_routings_erp_ref', 'routings', ['erp_ref'], unique=True, postgresql_where=sa.text('erp_ref IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_routings_erp_ref', table_name='routings', postgresql_where=sa.text('erp_ref IS NOT NULL'))
    op.drop_index(op.f('ix_routings_erp_ref'), table_name='routings')
    op.drop_column('routings', 'synced_at')
    op.drop_column('routings', 'erp_ref')
    op.drop_column('routings', 'source')
    op.drop_index('uq_products_erp_ref', table_name='products', postgresql_where=sa.text('erp_ref IS NOT NULL'))
    op.drop_index(op.f('ix_products_erp_ref'), table_name='products')
    op.drop_column('products', 'synced_at')
    op.drop_column('products', 'erp_ref')
    op.drop_column('products', 'source')
    op.drop_index('uq_boms_erp_ref', table_name='boms', postgresql_where=sa.text('erp_ref IS NOT NULL'))
    op.drop_index(op.f('ix_boms_erp_ref'), table_name='boms')
    op.drop_column('boms', 'synced_at')
    op.drop_column('boms', 'erp_ref')
    op.drop_column('boms', 'source')
    # ### end Alembic commands ###
