"""catch_up_rbac_quality_tables

Revision ID: 2afb2fd4624a
Revises: 0f9bb212c0a1
Create Date: 2026-08-10 12:03:34.715735
"""
from alembic import op
import sqlalchemy as sa


revision = '2afb2fd4624a'
down_revision = '0f9bb212c0a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('first_inspection_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('work_station_id', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trigger_new_order', sa.Boolean(), nullable=False),
    sa.Column('trigger_material_change', sa.Boolean(), nullable=False),
    sa.Column('trigger_tooling_change', sa.Boolean(), nullable=False),
    sa.Column('trigger_tool_change', sa.Boolean(), nullable=False),
    sa.Column('trigger_param_revision', sa.Boolean(), nullable=False),
    sa.Column('trigger_abnormal_restart', sa.Boolean(), nullable=False),
    sa.Column('trigger_shift_handover', sa.Boolean(), nullable=False),
    sa.Column('trigger_cold_start', sa.Boolean(), nullable=False),
    sa.Column('trigger_previous_failed', sa.Boolean(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('require_authorization', sa.Boolean(), nullable=False),
    sa.Column('authorized_roles', sa.JSON(), nullable=True),
    sa.Column('quarantine_on_fail', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['work_station_id'], ['work_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_first_inspection_configs_operation_id'), 'first_inspection_configs', ['operation_id'], unique=False)
    op.create_index(op.f('ix_first_inspection_configs_work_station_id'), 'first_inspection_configs', ['work_station_id'], unique=False)
    op.create_table('test_data_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('work_station_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['work_station_id'], ['work_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_data_templates_operation_id'), 'test_data_templates', ['operation_id'], unique=False)
    op.create_index(op.f('ix_test_data_templates_work_station_id'), 'test_data_templates', ['work_station_id'], unique=False)
    op.create_table('first_inspection_check_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('check_type', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('standard_value', sa.String(), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['first_inspection_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_first_inspection_check_items_config_id'), 'first_inspection_check_items', ['config_id'], unique=False)
    op.create_table('first_inspection_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('work_station_id', sa.Integer(), nullable=False),
    sa.Column('serial_unit_id', sa.Integer(), nullable=True),
    sa.Column('trigger_reason', sa.String(), nullable=False),
    sa.Column('trigger_detail', sa.String(), nullable=True),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('inspected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('released_by_id', sa.Integer(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_remark', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['first_inspection_configs.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['released_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['serial_unit_id'], ['serial_units.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.ForeignKeyConstraint(['work_station_id'], ['work_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_first_inspection_records_serial_unit_id'), 'first_inspection_records', ['serial_unit_id'], unique=False)
    op.create_index(op.f('ix_first_inspection_records_work_order_id'), 'first_inspection_records', ['work_order_id'], unique=False)
    op.create_table('test_data_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('field_type', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('standard_value', sa.String(), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('display_group', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['test_data_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_data_fields_template_id'), 'test_data_fields', ['template_id'], unique=False)
    op.create_table('first_inspection_check_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('check_item_id', sa.Integer(), nullable=False),
    sa.Column('check_item_name', sa.String(), nullable=False),
    sa.Column('result_type', sa.String(), nullable=False),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.Column('numeric_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('text_value', sa.String(), nullable=True),
    sa.Column('is_pass', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['check_item_id'], ['first_inspection_check_items.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['first_inspection_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_first_inspection_check_results_record_id'), 'first_inspection_check_results', ['record_id'], unique=False)
    op.create_table('first_inspection_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('last_inspection_record_id', sa.Integer(), nullable=True),
    sa.Column('last_passed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_material_batch', sa.String(), nullable=True),
    sa.Column('current_tooling_id', sa.String(), nullable=True),
    sa.Column('current_param_version', sa.String(), nullable=True),
    sa.Column('last_produced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_shift_date', sa.String(), nullable=True),
    sa.Column('is_abnormal_state', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_inspection_record_id'], ['first_inspection_records.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_first_inspection_states_operation_id'), 'first_inspection_states', ['operation_id'], unique=False)
    op.create_index(op.f('ix_first_inspection_states_work_order_id'), 'first_inspection_states', ['work_order_id'], unique=False)
    op.create_index('uq_wo_op_state', 'first_inspection_states', ['work_order_id', 'operation_id'], unique=True)
    op.create_table('test_data_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('operation_record_id', sa.Integer(), nullable=False),
    sa.Column('serial_unit_id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('work_station_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('overall_result', sa.String(), nullable=False),
    sa.Column('test_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['operation_record_id'], ['operation_records.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['serial_unit_id'], ['serial_units.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['test_data_templates.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.ForeignKeyConstraint(['work_station_id'], ['work_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_data_records_operation_record_id'), 'test_data_records', ['operation_record_id'], unique=False)
    op.create_index(op.f('ix_test_data_records_serial_unit_id'), 'test_data_records', ['serial_unit_id'], unique=False)
    op.create_index(op.f('ix_test_data_records_work_order_id'), 'test_data_records', ['work_order_id'], unique=False)
    op.create_table('test_data_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('field_code', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('value_type', sa.String(), nullable=False),
    sa.Column('numeric_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.Column('text_value', sa.String(), nullable=True),
    sa.Column('is_pass', sa.Boolean(), nullable=True),
    sa.Column('out_of_spec', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['test_data_fields.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['test_data_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_data_values_record_id'), 'test_data_values', ['record_id'], unique=False)
    # Add users.role_id (FK to roles.id); make existing users.role nullable for backward compat
    # (model only writes role_id now; legacy role column kept readable for dependencies.py/quality_service.py)
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               nullable=True)
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_users_role_id_roles', 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_role_id_roles', 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               nullable=False)
    op.drop_index(op.f('ix_test_data_values_record_id'), table_name='test_data_values')
    op.drop_table('test_data_values')
    op.drop_index(op.f('ix_test_data_records_work_order_id'), table_name='test_data_records')
    op.drop_index(op.f('ix_test_data_records_serial_unit_id'), table_name='test_data_records')
    op.drop_index(op.f('ix_test_data_records_operation_record_id'), table_name='test_data_records')
    op.drop_table('test_data_records')
    op.drop_index('uq_wo_op_state', table_name='first_inspection_states')
    op.drop_index(op.f('ix_first_inspection_states_work_order_id'), table_name='first_inspection_states')
    op.drop_index(op.f('ix_first_inspection_states_operation_id'), table_name='first_inspection_states')
    op.drop_table('first_inspection_states')
    op.drop_index(op.f('ix_first_inspection_check_results_record_id'), table_name='first_inspection_check_results')
    op.drop_table('first_inspection_check_results')
    op.drop_index(op.f('ix_test_data_fields_template_id'), table_name='test_data_fields')
    op.drop_table('test_data_fields')
    op.drop_index(op.f('ix_first_inspection_records_work_order_id'), table_name='first_inspection_records')
    op.drop_index(op.f('ix_first_inspection_records_serial_unit_id'), table_name='first_inspection_records')
    op.drop_table('first_inspection_records')
    op.drop_index(op.f('ix_first_inspection_check_items_config_id'), table_name='first_inspection_check_items')
    op.drop_table('first_inspection_check_items')
    op.drop_index(op.f('ix_test_data_templates_work_station_id'), table_name='test_data_templates')
    op.drop_index(op.f('ix_test_data_templates_operation_id'), table_name='test_data_templates')
    op.drop_table('test_data_templates')
    op.drop_index(op.f('ix_first_inspection_configs_work_station_id'), table_name='first_inspection_configs')
    op.drop_index(op.f('ix_first_inspection_configs_operation_id'), table_name='first_inspection_configs')
    op.drop_table('first_inspection_configs')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
