"""add skill and operator_skill tables

Revision ID: 2b6bd32b9ae7
Revises: 20fc7d5e9c59
Create Date: 2026-08-05 16:32:20.962902
"""
from alembic import op
import sqlalchemy as sa


revision = '2b6bd32b9ae7'
down_revision = '20fc7d5e9c59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_level', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_code'), 'skill', ['code'], unique=True)
    op.create_table('operator_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_operator_skill_user_skill')
    )
    op.create_foreign_key('fk_operations_required_skill', 'operations', 'skill', ['required_skill_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_operations_required_skill', 'operations', type_='foreignkey')
    op.drop_table('operator_skill')
    op.drop_index(op.f('ix_skill_code'), table_name='skill')
    op.drop_table('skill')
    # ### end Alembic commands ###
