"""add is_counted to serial_units

Revision ID: 3192a470203e
Revises: f8a8c47523ff
Create Date: 2026-08-04 12:49:21.590304
"""
from alembic import op
import sqlalchemy as sa


revision = '3192a470203e'
down_revision = 'f8a8c47523ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serial_units', sa.Column(
        'is_counted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serial_units', 'is_counted')
    # ### end Alembic commands ###
