"""add uq_operation_routing_code unique constraint

Revision ID: 3cc26e0832b0
Revises: 7eddb2bee529
Create Date: 2026-08-04 18:35:25.816300
"""
from alembic import op
import sqlalchemy as sa


revision = '3cc26e0832b0'
down_revision = '7eddb2bee529'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_operation_routing_code', 'operations', ['routing_id', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_operation_routing_code', 'operations', type_='unique')
    # ### end Alembic commands ###
