"""add carrier_binding.unbound_reason

Revision ID: 43985d47f2a9
Revises: 776a57eedc0f
Create Date: 2026-08-06 15:58:42.466855
"""
from alembic import op
import sqlalchemy as sa


revision = '43985d47f2a9'
down_revision = '776a57eedc0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carrier_binding', sa.Column('unbound_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carrier_binding', 'unbound_reason')
    # ### end Alembic commands ###
