"""add operation_record_id to genealogy_binds

Revision ID: 45ebdd36fa81
Revises: cbe8c0b80567
Create Date: 2026-08-04 17:46:54.782580
"""
from alembic import op
import sqlalchemy as sa


revision = '45ebdd36fa81'
down_revision = 'cbe8c0b80567'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genealogy_binds', sa.Column('operation_record_id', sa.Integer(), nullable=True))
    op.create_foreign_key('genealogy_binds_operation_record_id_fkey', 'genealogy_binds', 'operation_records', ['operation_record_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('genealogy_binds_operation_record_id_fkey', 'genealogy_binds', type_='foreignkey')
    op.drop_column('genealogy_binds', 'operation_record_id')
    # ### end Alembic commands ###
