"""create product

Revision ID: 4b1680ddb7bb
Revises: 888231b65974
Create Date: 2026-07-31 17:41:36.447709
"""
from alembic import op
import sqlalchemy as sa


revision = '4b1680ddb7bb'
down_revision = '888231b65974'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('spec', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('track_mode', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
