"""add carrier_code and carrier_binding

Revision ID: 776a57eedc0f
Revises: 2b6bd32b9ae7
Create Date: 2026-08-06 15:08:49.681986
"""
from alembic import op
import sqlalchemy as sa


revision = '776a57eedc0f'
down_revision = '2b6bd32b9ae7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrier_binding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_unit_id', sa.Integer(), nullable=False),
    sa.Column('carrier_code', sa.String(), nullable=False),
    sa.Column('bound_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['serial_unit_id'], ['serial_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('serial_units', sa.Column('carrier_code', sa.String(), nullable=True))
    op.create_index('uq_active_carrier', 'serial_units', ['carrier_code'], unique=True, postgresql_where=sa.text('carrier_code IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_carrier', table_name='serial_units', postgresql_where=sa.text('carrier_code IS NOT NULL'))
    op.drop_column('serial_units', 'carrier_code')
    op.drop_table('carrier_binding')
    # ### end Alembic commands ###
