"""drop legacy stations routing_steps station_passes and genealogy station_pass_id

Revision ID: 7eddb2bee529
Revises: 45ebdd36fa81
Create Date: 2026-08-04 18:15:02.274914
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '7eddb2bee529'
down_revision = '45ebdd36fa81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 先摘 genealogy_binds.station_pass_id（FK 指向 station_passes），再 drop station_passes
    op.drop_constraint(op.f('genealogy_binds_station_pass_id_fkey'), 'genealogy_binds', type_='foreignkey')
    op.drop_column('genealogy_binds', 'station_pass_id')
    # station_passes 引用 stations/routing_steps → 先 drop station_passes，再 drop 后两者
    op.drop_table('station_passes')
    op.drop_table('routing_steps')
    op.drop_index(op.f('ix_stations_code'), table_name='stations')
    op.drop_table('stations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('stations_pkey'))
    )
    op.create_index(op.f('ix_stations_code'), 'stations', ['code'], unique=True)
    op.create_table('routing_steps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('routing_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seq', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_mandatory', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('binding_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['routing_id'], ['routings.id'], name=op.f('routing_steps_routing_id_fkey')),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('routing_steps_station_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('routing_steps_pkey')),
    sa.UniqueConstraint('routing_id', 'seq', name=op.f('uq_routing_step_seq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('station_passes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('serial_unit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('work_order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('routing_step_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('operator_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pass_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('result', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('remark', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], name=op.f('station_passes_operator_id_fkey')),
    sa.ForeignKeyConstraint(['routing_step_id'], ['routing_steps.id'], name=op.f('station_passes_routing_step_id_fkey')),
    sa.ForeignKeyConstraint(['serial_unit_id'], ['serial_units.id'], name=op.f('station_passes_serial_unit_id_fkey')),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('station_passes_station_id_fkey')),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('station_passes_work_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('station_passes_pkey'))
    )
    op.add_column('genealogy_binds', sa.Column('station_pass_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('genealogy_binds_station_pass_id_fkey'), 'genealogy_binds', 'station_passes', ['station_pass_id'], ['id'])
    # ### end Alembic commands ###
