"""work_order line_id and serial_unit operation_seq

Revision ID: 882abdd101fa
Revises: 92982817c607
Create Date: 2026-08-04 17:34:03.718381
"""
from alembic import op
import sqlalchemy as sa


revision = '882abdd101fa'
down_revision = '92982817c607'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serial_units', sa.Column('current_operation_seq', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('serial_units_current_station_id_fkey'), 'serial_units', type_='foreignkey')
    op.drop_column('serial_units', 'current_step_seq')
    op.drop_column('serial_units', 'current_station_id')
    op.add_column('work_orders', sa.Column('line_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'work_orders', 'lines', ['line_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.drop_column('work_orders', 'line_id')
    op.add_column('serial_units', sa.Column('current_station_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('serial_units', sa.Column('current_step_seq', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('serial_units_current_station_id_fkey'), 'serial_units', 'stations', ['current_station_id'], ['id'])
    op.drop_column('serial_units', 'current_operation_seq')
    # ### end Alembic commands ###
