"""create serial_unit and station_pass

Revision ID: 9d676b1fc713
Revises: d98b33d96e5e
Create Date: 2026-08-03 10:16:06.426499
"""
from alembic import op
import sqlalchemy as sa


revision = '9d676b1fc713'
down_revision = 'd98b33d96e5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serial_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sn', sa.String(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_step_seq', sa.Integer(), nullable=False),
    sa.Column('current_station_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serial_units_sn'), 'serial_units', ['sn'], unique=True)
    op.create_table('station_passes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_unit_id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('routing_step_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('pass_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['routing_step_id'], ['routing_steps.id'], ),
    sa.ForeignKeyConstraint(['serial_unit_id'], ['serial_units.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('station_passes')
    op.drop_index(op.f('ix_serial_units_sn'), table_name='serial_units')
    op.drop_table('serial_units')
    # ### end Alembic commands ###
