"""add operation_record and operation_param

Revision ID: cbe8c0b80567
Revises: 882abdd101fa
Create Date: 2026-08-04 17:41:34.886186
"""
from alembic import op
import sqlalchemy as sa


revision = 'cbe8c0b80567'
down_revision = '882abdd101fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_unit_id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('work_station_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['serial_unit_id'], ['serial_units.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.ForeignKeyConstraint(['work_station_id'], ['work_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_record_id', sa.Integer(), nullable=False),
    sa.Column('param_key', sa.String(), nullable=False),
    sa.Column('param_value', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_record_id'], ['operation_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_params')
    op.drop_table('operation_records')
    # ### end Alembic commands ###
