"""create bom

Revision ID: cd748fb65f62
Revises: 48a4fa198b1c
Create Date: 2026-07-31 17:56:51.388391
"""
from alembic import op
import sqlalchemy as sa


revision = 'cd748fb65f62'
down_revision = '48a4fa198b1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('component_product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('track_mode', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], ),
    sa.ForeignKeyConstraint(['component_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bom_id', 'component_product_id', name='uq_bom_item_component')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bom_items')
    op.drop_table('boms')
    # ### end Alembic commands ###
