"""add uq_active_component_sn partial unique index

Revision ID: e9f462d24c1a
Revises: 3192a470203e
Create Date: 2026-08-04 12:50:01.577163
"""
from alembic import op
import sqlalchemy as sa


revision = 'e9f462d24c1a'
down_revision = '3192a470203e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_active_component_sn', 'genealogy_binds', ['component_sn'], unique=True, postgresql_where=sa.text("status = 'active' AND component_sn IS NOT NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_component_sn', table_name='genealogy_binds', postgresql_where=sa.text("status = 'active' AND component_sn IS NOT NULL"))
    # ### end Alembic commands ###
