"""create genealogy_bind

Revision ID: f8a8c47523ff
Revises: 704daeb1e281
Create Date: 2026-08-04 12:09:59.511138
"""
from alembic import op
import sqlalchemy as sa


revision = 'f8a8c47523ff'
down_revision = '704daeb1e281'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genealogy_binds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_sn_id', sa.Integer(), nullable=False),
    sa.Column('component_product_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(), nullable=False),
    sa.Column('component_sn', sa.String(), nullable=True),
    sa.Column('component_batch_no', sa.String(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('bind_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('station_pass_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('unbind_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unbind_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['component_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_sn_id'], ['serial_units.id'], ),
    sa.ForeignKeyConstraint(['station_pass_id'], ['station_passes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genealogy_binds_component_batch_no'), 'genealogy_binds', ['component_batch_no'], unique=False)
    op.create_index(op.f('ix_genealogy_binds_component_sn'), 'genealogy_binds', ['component_sn'], unique=False)
    op.create_index(op.f('ix_genealogy_binds_parent_sn_id'), 'genealogy_binds', ['parent_sn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genealogy_binds_parent_sn_id'), table_name='genealogy_binds')
    op.drop_index(op.f('ix_genealogy_binds_component_sn'), table_name='genealogy_binds')
    op.drop_index(op.f('ix_genealogy_binds_component_batch_no'), table_name='genealogy_binds')
    op.drop_table('genealogy_binds')
    # ### end Alembic commands ###
