"""create sn_rule

Revision ID: fc9807c2166a
Revises: cd748fb65f62
Create Date: 2026-07-31 18:03:42.699178
"""
from alembic import op
import sqlalchemy as sa


revision = 'fc9807c2166a'
down_revision = 'cd748fb65f62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sn_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('seq_reset', sa.String(), nullable=False),
    sa.Column('current_seq', sa.Integer(), nullable=False),
    sa.Column('seq_period_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sn_rules_code'), 'sn_rules', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sn_rules_code'), table_name='sn_rules')
    op.drop_table('sn_rules')
    # ### end Alembic commands ###
